name: pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: true
  release-check:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'harrydowning'
    steps:
      - run: true
  release:
    runs-on: ubuntu-latest
    needs: release-check
    if: contains(github.event.head_commit.message, '[release]')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm pack
      - run: npm run release
        env:
          GH_TOKEN: ${{ github.token }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
