name: pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node-pipeline:
    uses: harrydowning/github-workflows/.github/workflows/node-pipeline.yml@v1.0.1
    with:
      repository-owner: harrydowning
      node-version: "20"
      release-run: | # shell
        npm i
        npm run build
        npm pack
        npm run release
        npm publish
    secrets: inherit
